language: python

python:
 - 3.6

install:
 - sudo apt-get install unixodbc-dev
 - pip install -r requirements.txt
 - pip install codecov
 - pip install pytest pytest-cov

script:
 - pytest --cov=./

after_success:
  - codecov
  - cd docs && make html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubtoken
  local_dir: docs/build/html
  keep_history: true
